# mkdocs.yml
site_name: HDRUK Avoidable Admissions

theme:
  name: "material"
  nav_style: dark

plugins:
  - search
  - mkdocstrings

nav:
  - Index: index.md
  - Study Documentation:
    # - Avoidable Admissions: documentation/avoidable_admissions_sap.md
    # - Winter Pressures Statistical Analysis Plan: documentation/winter_pressures_sap.md
    - Global Variables Statistical Analysis Plan: documentation/global_variables.md
  - Data Models: 
    - Admitted Patient Care: data_models/admitted_patient_care_data_model.md
    - Emergency Care: data_models/emergency_care_data_model.md
  - How To Guides: 
    - New to Python?: how_to_guides/new_to_python.md
  - Code: code/code.md

markdown_extensions:
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HDR_UK